// !!! DO NOT EDIT !!! -- automatically generated by scripts/assets.js

import assetCollectionReferenceData from 'url:../../images/edg/asset-collection-reference-data.svg';
import assetCollectionTaxonomy from 'url:../../images/edg/asset-collection-taxonomy.svg';
import dataset from 'url:../../images/edg/dataset.svg';
import datasetCollection from 'url:../../images/edg/dataset-collection.svg';
import shacl from 'url:../../images/edg/shacl.svg';

export {assetCollectionReferenceData, assetCollectionTaxonomy, dataset, datasetCollection, shacl};
