// !!! DO NOT EDIT !!! -- automatically generated by scripts/assets.js

import cloudRun from 'url:../../images/gcp/cloud-run.svg';
import dataCatalog from 'url:../../images/gcp/data-catalog.svg';
import firestore from 'url:../../images/gcp/firestore.svg';
import gke from 'url:../../images/gcp/gke.svg';

export {cloudRun, dataCatalog, firestore, gke};
