// !!! DO NOT EDIT !!! -- automatically generated by scripts/assets.js

const absMember = new URL('https://google.com');
const activeDirectory = new URL('https://google.com');
const activeDirectoryConnectHealth = new URL('https://google.com');
const activityLog = new URL('https://google.com');
const adB2C = new URL('https://google.com');
const adDomainServices = new URL('https://google.com');
const adRolesAndAdministrators = new URL('https://google.com');
const advisor = new URL('https://google.com');
const alerts = new URL('https://google.com');
const allResources = new URL('https://google.com');
const analysisServices = new URL('https://google.com');
const apiManagementServices = new URL('https://google.com');
const appRegistrations = new URL('https://google.com');
const appServiceCertificates = new URL('https://google.com');
const appServiceDomains = new URL('https://google.com');
const appServiceEnvironments = new URL('https://google.com');
const appServicePlans = new URL('https://google.com');
const appServices = new URL('https://google.com');
const applicationInsights = new URL('https://google.com');
const arc = new URL('https://google.com');
const automationAccounts = new URL('https://google.com');
const availabilitySets = new URL('https://google.com');
const avs = new URL('https://google.com');
const backlog = new URL('https://google.com');
const batchAccounts = new URL('https://google.com');
const bizTalk = new URL('https://google.com');
const blobBlock = new URL('https://google.com');
const blobPage = new URL('https://google.com');
const blockchainService = new URL('https://google.com');
const blueprints = new URL('https://google.com');
const botServices = new URL('https://google.com');
const branch = new URL('https://google.com');
const browser = new URL('https://google.com');
const bug = new URL('https://google.com');
const builds = new URL('https://google.com');
const cache = new URL('https://google.com');
const cacheRedis = new URL('https://google.com');
const capacity = new URL('https://google.com');
const cdnProfiles = new URL('https://google.com');
const cloudServicesClassic = new URL('https://google.com');
const code = new URL('https://google.com');
const cognitiveServices = new URL('https://google.com');
const commit = new URL('https://google.com');
const compliance = new URL('https://google.com');
const consortium = new URL('https://google.com');
const containerInstances = new URL('https://google.com');
const containerRegistries = new URL('https://google.com');
const containerServicesDeprecated = new URL('https://google.com');
const controls = new URL('https://google.com');
const controlsHorizontal = new URL('https://google.com');
const cosmosDb = new URL('https://google.com');
const costAlerts = new URL('https://google.com');
const costAnalysis = new URL('https://google.com');
const costBudgets = new URL('https://google.com');
const costManagement = new URL('https://google.com');
const counter = new URL('https://google.com');
const cubes = new URL('https://google.com');
const dashboard = new URL('https://google.com');
const dataBox = new URL('https://google.com');
const dataBoxEdge = new URL('https://google.com');
const dataCatalog = new URL('https://google.com');
const dataExplorerClusters = new URL('https://google.com');
const dataFactory = new URL('https://google.com');
const dataLakeStoreGen1 = new URL('https://google.com');
const databaseMariadbServer = new URL('https://google.com');
const databaseMigrationServices = new URL('https://google.com');
const databaseMysqlServer = new URL('https://google.com');
const databasePostgresqlServer = new URL('https://google.com');
const ddosProtectionPlans = new URL('https://google.com');
const devConsole = new URL('https://google.com');
const deviceProvisioningServices = new URL('https://google.com');
const deviceSecurityApple = new URL('https://google.com');
const deviceSecurityGoogle = new URL('https://google.com');
const deviceSecurityWindows = new URL('https://google.com');
const devops = new URL('https://google.com');
const devtestLabs = new URL('https://google.com');
const diagnosticsSettings = new URL('https://google.com');
const digitalTwins = new URL('https://google.com');
const diskEncryptionSets = new URL('https://google.com');
const disks = new URL('https://google.com');
const disksClassic = new URL('https://google.com');
const disksSnapshots = new URL('https://google.com');
const dnsZones = new URL('https://google.com');
const download = new URL('https://google.com');
const education = new URL('https://google.com');
const elasticJobAgents = new URL('https://google.com');
const elixir = new URL('https://google.com');
const elixirPurple = new URL('https://google.com');
const enterpriseApplications = new URL('https://google.com');
const error = new URL('https://google.com');
const eventGridDomains = new URL('https://google.com');
const eventGridSubscriptions = new URL('https://google.com');
const eventGridTopics = new URL('https://google.com');
const eventHubClusters = new URL('https://google.com');
const eventHubs = new URL('https://google.com');
const extensions = new URL('https://google.com');
const file = new URL('https://google.com');
const files = new URL('https://google.com');
const firewallManager = new URL('https://google.com');
const folderBlank = new URL('https://google.com');
const folderWebsite = new URL('https://google.com');
const frontDoors = new URL('https://google.com');
const ftp = new URL('https://google.com');
const functionApps = new URL('https://google.com');
const gear = new URL('https://google.com');
const globe = new URL('https://google.com');
const globeError = new URL('https://google.com');
const globeSuccess = new URL('https://google.com');
const globeWarning = new URL('https://google.com');
const groups = new URL('https://google.com');
const guide = new URL('https://google.com');
const hdInsightClusters = new URL('https://google.com');
const heart = new URL('https://google.com');
const helpAndSupport = new URL('https://google.com');
const identityGovernance = new URL('https://google.com');
const image = new URL('https://google.com');
const imageDefinitions = new URL('https://google.com');
const imageVersions = new URL('https://google.com');
const images = new URL('https://google.com');
const information = new URL('https://google.com');
const infrastructureBackup = new URL('https://google.com');
const inputOutput = new URL('https://google.com');
const instancePools = new URL('https://google.com');
const integrationAccounts = new URL('https://google.com');
const iotCentralApplications = new URL('https://google.com');
const iotHub = new URL('https://google.com');
const ipGroups = new URL('https://google.com');
const journeyHub = new URL('https://google.com');
const kubernetesServices = new URL('https://google.com');
const labServices = new URL('https://google.com');
const launchPortal = new URL('https://google.com');
const learn = new URL('https://google.com');
const lighthouse = new URL('https://google.com');
const loadBalancers = new URL('https://google.com');
const loadTest = new URL('https://google.com');
const location = new URL('https://google.com');
const logAnalyticsWorkspaces = new URL('https://google.com');
const logStreaming = new URL('https://google.com');
const logicApps = new URL('https://google.com');
const machinesAzureArc = new URL('https://google.com');
const managedApplicationsCenter = new URL('https://google.com');
const managedDatabase = new URL('https://google.com');
const managementGroups = new URL('https://google.com');
const managementPortal = new URL('https://google.com');
const mapsAccounts = new URL('https://google.com');
const marketplace = new URL('https://google.com');
const media = new URL('https://google.com');
const mediaFile = new URL('https://google.com');
const meshApplications = new URL('https://google.com');
const metrics = new URL('https://google.com');
const migrate = new URL('https://google.com');
const mobile = new URL('https://google.com');
const mobileEngagement = new URL('https://google.com');
const monitor = new URL('https://google.com');
const multiTenancy = new URL('https://google.com');
const myCustomers = new URL('https://google.com');
const networkSecurityGroups = new URL('https://google.com');
const networkWatcher = new URL('https://google.com');
const notificationHubs = new URL('https://google.com');
const offers = new URL('https://google.com');
const operationLogClassic = new URL('https://google.com');
const osImagesClassic = new URL('https://google.com');
const outboundConnection = new URL('https://google.com');
const plans = new URL('https://google.com');
const policy = new URL('https://google.com');
const power = new URL('https://google.com');
const powerUp = new URL('https://google.com');
const powershell = new URL('https://google.com');
const preview = new URL('https://google.com');
const privateLink = new URL('https://google.com');
const privateLinkService = new URL('https://google.com');
const processExplorer = new URL('https://google.com');
const productionReadyDatabase = new URL('https://google.com');
const publicIpAddresses = new URL('https://google.com');
const publicIpAddressesClassic = new URL('https://google.com');
const quickstartCenter = new URL('https://google.com');
const recent = new URL('https://google.com');
const recoveryServicesVaults = new URL('https://google.com');
const relays = new URL('https://google.com');
const remoteRendering = new URL('https://google.com');
const reservations = new URL('https://google.com');
const resourceGraphExplorer = new URL('https://google.com');
const resourceGroupList = new URL('https://google.com');
const resourceGroups = new URL('https://google.com');
const resourceLinked = new URL('https://google.com');
const routeFilters = new URL('https://google.com');
const sapAzureMonitor = new URL('https://google.com');
const scale = new URL('https://google.com');
const scheduler = new URL('https://google.com');
const search = new URL('https://google.com');
const searchGrid = new URL('https://google.com');
const searchServices = new URL('https://google.com');
const serverFarm = new URL('https://google.com');
const serviceBus = new URL('https://google.com');
const serviceFabricClusters = new URL('https://google.com');
const serviceHealth = new URL('https://google.com');
const serviceProviders = new URL('https://google.com');
const sharedImageGalleries = new URL('https://google.com');
const softwareAsAService = new URL('https://google.com');
const solutions = new URL('https://google.com');
const sqlDataWarehouses = new URL('https://google.com');
const sqlDatabase = new URL('https://google.com');
const sqlElasticPools = new URL('https://google.com');
const sqlManagedInstance = new URL('https://google.com');
const sqlServer = new URL('https://google.com');
const sqlServerStretchDatabases = new URL('https://google.com');
const sqlVm = new URL('https://google.com');
const ssd = new URL('https://google.com');
const stack = new URL('https://google.com');
const storageAzureFiles = new URL('https://google.com');
const storageContainer = new URL('https://google.com');
const storageQueue = new URL('https://google.com');
const streamAnalyticsJobs = new URL('https://google.com');
const subscriptions = new URL('https://google.com');
const synapseAnalytics = new URL('https://google.com');
const table = new URL('https://google.com');
const tags = new URL('https://google.com');
const tfsVcRepository = new URL('https://google.com');
const timeSeriesInsightsEnvironments = new URL('https://google.com');
const timeSeriesInsightsEventSources = new URL('https://google.com');
const tokenService = new URL('https://google.com');
const toolbox = new URL('https://google.com');
const trafficManagerProfiles = new URL('https://google.com');
const updates = new URL('https://google.com');
const userPrivacy = new URL('https://google.com');
const userSubscriptions = new URL('https://google.com');
const users = new URL('https://google.com');
const versions = new URL('https://google.com');
const virtualClusters = new URL('https://google.com');
const virtualMachine = new URL('https://google.com');
const virtualMachinesClassic = new URL('https://google.com');
const virtualNetworkGateways = new URL('https://google.com');
const virtualNetworks = new URL('https://google.com');
const vmImagesClassic = new URL('https://google.com');
const vmScaleSets = new URL('https://google.com');
const webSlots = new URL('https://google.com');
const webTest = new URL('https://google.com');
const websitePower = new URL('https://google.com');
const websiteStaging = new URL('https://google.com');
const workbooks = new URL('https://google.com');
const workflow = new URL('https://google.com');
const workspaces = new URL('https://google.com');

export {
  absMember,
  activeDirectory,
  activeDirectoryConnectHealth,
  activityLog,
  adB2C,
  adDomainServices,
  adRolesAndAdministrators,
  advisor,
  alerts,
  allResources,
  analysisServices,
  apiManagementServices,
  appRegistrations,
  appServiceCertificates,
  appServiceDomains,
  appServiceEnvironments,
  appServicePlans,
  appServices,
  applicationInsights,
  arc,
  automationAccounts,
  availabilitySets,
  avs,
  backlog,
  batchAccounts,
  bizTalk,
  blobBlock,
  blobPage,
  blockchainService,
  blueprints,
  botServices,
  branch,
  browser,
  bug,
  builds,
  cache,
  cacheRedis,
  capacity,
  cdnProfiles,
  cloudServicesClassic,
  code,
  cognitiveServices,
  commit,
  compliance,
  consortium,
  containerInstances,
  containerRegistries,
  containerServicesDeprecated,
  controls,
  controlsHorizontal,
  cosmosDb,
  costAlerts,
  costAnalysis,
  costBudgets,
  costManagement,
  counter,
  cubes,
  dashboard,
  dataBox,
  dataBoxEdge,
  dataCatalog,
  dataExplorerClusters,
  dataFactory,
  dataLakeStoreGen1,
  databaseMariadbServer,
  databaseMigrationServices,
  databaseMysqlServer,
  databasePostgresqlServer,
  ddosProtectionPlans,
  devConsole,
  deviceProvisioningServices,
  deviceSecurityApple,
  deviceSecurityGoogle,
  deviceSecurityWindows,
  devops,
  devtestLabs,
  diagnosticsSettings,
  digitalTwins,
  diskEncryptionSets,
  disks,
  disksClassic,
  disksSnapshots,
  dnsZones,
  download,
  education,
  elasticJobAgents,
  elixir,
  elixirPurple,
  enterpriseApplications,
  error,
  eventGridDomains,
  eventGridSubscriptions,
  eventGridTopics,
  eventHubClusters,
  eventHubs,
  extensions,
  file,
  files,
  firewallManager,
  folderBlank,
  folderWebsite,
  frontDoors,
  ftp,
  functionApps,
  gear,
  globe,
  globeError,
  globeSuccess,
  globeWarning,
  groups,
  guide,
  hdInsightClusters,
  heart,
  helpAndSupport,
  identityGovernance,
  image,
  imageDefinitions,
  imageVersions,
  images,
  information,
  infrastructureBackup,
  inputOutput,
  instancePools,
  integrationAccounts,
  iotCentralApplications,
  iotHub,
  ipGroups,
  journeyHub,
  kubernetesServices,
  labServices,
  launchPortal,
  learn,
  lighthouse,
  loadBalancers,
  loadTest,
  location,
  logAnalyticsWorkspaces,
  logStreaming,
  logicApps,
  machinesAzureArc,
  managedApplicationsCenter,
  managedDatabase,
  managementGroups,
  managementPortal,
  mapsAccounts,
  marketplace,
  media,
  mediaFile,
  meshApplications,
  metrics,
  migrate,
  mobile,
  mobileEngagement,
  monitor,
  multiTenancy,
  myCustomers,
  networkSecurityGroups,
  networkWatcher,
  notificationHubs,
  offers,
  operationLogClassic,
  osImagesClassic,
  outboundConnection,
  plans,
  policy,
  power,
  powerUp,
  powershell,
  preview,
  privateLink,
  privateLinkService,
  processExplorer,
  productionReadyDatabase,
  publicIpAddresses,
  publicIpAddressesClassic,
  quickstartCenter,
  recent,
  recoveryServicesVaults,
  relays,
  remoteRendering,
  reservations,
  resourceGraphExplorer,
  resourceGroupList,
  resourceGroups,
  resourceLinked,
  routeFilters,
  sapAzureMonitor,
  scale,
  scheduler,
  search,
  searchGrid,
  searchServices,
  serverFarm,
  serviceBus,
  serviceFabricClusters,
  serviceHealth,
  serviceProviders,
  sharedImageGalleries,
  softwareAsAService,
  solutions,
  sqlDataWarehouses,
  sqlDatabase,
  sqlElasticPools,
  sqlManagedInstance,
  sqlServer,
  sqlServerStretchDatabases,
  sqlVm,
  ssd,
  stack,
  storageAzureFiles,
  storageContainer,
  storageQueue,
  streamAnalyticsJobs,
  subscriptions,
  synapseAnalytics,
  table,
  tags,
  tfsVcRepository,
  timeSeriesInsightsEnvironments,
  timeSeriesInsightsEventSources,
  tokenService,
  toolbox,
  trafficManagerProfiles,
  updates,
  userPrivacy,
  userSubscriptions,
  users,
  versions,
  virtualClusters,
  virtualMachine,
  virtualMachinesClassic,
  virtualNetworkGateways,
  virtualNetworks,
  vmImagesClassic,
  vmScaleSets,
  webSlots,
  webTest,
  websitePower,
  websiteStaging,
  workbooks,
  workflow,
  workspaces,
};
