// !!! DO NOT EDIT !!! -- automatically generated by scripts/assets.js

const aiplatform = new URL('https://google.com');
const apianalytics = new URL('https://google.com');
const apigeeapiplatform = new URL('https://google.com');
const apigeesense = new URL('https://google.com');
const apimonetization = new URL('https://google.com');
const apis = new URL('https://google.com');
const appengine = new URL('https://google.com');
const armor = new URL('https://google.com');
const artifactRegistry = new URL('https://google.com');
const automl = new URL('https://google.com');
const beyondcorp = new URL('https://google.com');
const bigquery = new URL('https://google.com');
const bigtable = new URL('https://google.com');
const build = new URL('https://google.com');
const cdn = new URL('https://google.com');
const cloudDebugger = new URL('https://google.com');
const cloudRun = new URL('https://google.com');
const composer = new URL('https://google.com');
const computeEngine = new URL('https://google.com');
const containerOptimizedOs = new URL('https://google.com');
const dataCatalog = new URL('https://google.com');
const dataLab = new URL('https://google.com');
const dataLossPreventionApi = new URL('https://google.com');
const dataStudio = new URL('https://google.com');
const dataflow = new URL('https://google.com');
const dataprep = new URL('https://google.com');
const dataproc = new URL('https://google.com');
const datastore = new URL('https://google.com');
const deploymentManager = new URL('https://google.com');
const developerPortal = new URL('https://google.com');
const dialogflow = new URL('https://google.com');
const dns = new URL('https://google.com');
const eTpu = new URL('https://google.com');
const endpoints = new URL('https://google.com');
const errorReporting = new URL('https://google.com');
const externalIpAddresses = new URL('https://google.com');
const filestore = new URL('https://google.com');
const firestore = new URL('https://google.com');
const firewallRules = new URL('https://google.com');
const functions = new URL('https://google.com');
const generic = new URL('https://google.com');
const genomics = new URL('https://google.com');
const gke = new URL('https://google.com');
const gkeOnPrem = new URL('https://google.com');
const gpu = new URL('https://google.com');
const iam = new URL('https://google.com');
const interconnect = new URL('https://google.com');
const iotCore = new URL('https://google.com');
const jobsApi = new URL('https://google.com');
const keyAccessJustifications = new URL('https://google.com');
const loadBalancing = new URL('https://google.com');
const logging = new URL('https://google.com');
const memorystore = new URL('https://google.com');
const monitoring = new URL('https://google.com');
const naturalLanguageApi = new URL('https://google.com');
const network = new URL('https://google.com');
const partnerInterconnect = new URL('https://google.com');
const persistentDisk = new URL('https://google.com');
const premiumNetworkTier = new URL('https://google.com');
const pubSub = new URL('https://google.com');
const router = new URL('https://google.com');
const routes = new URL('https://google.com');
const securityCommandCenter = new URL('https://google.com');
const spanner = new URL('https://google.com');
const speechToText = new URL('https://google.com');
const sql = new URL('https://google.com');
const stackdriver = new URL('https://google.com');
const standardNetworkTier = new URL('https://google.com');
const storage = new URL('https://google.com');
const textToSpeech = new URL('https://google.com');
const toolsForPowershell = new URL('https://google.com');
const trace = new URL('https://google.com');
const transferAppliance = new URL('https://google.com');
const translationApi = new URL('https://google.com');
const videoIntelligenceApi = new URL('https://google.com');
const virtualPrivateCloud = new URL('https://google.com');
const visionApi = new URL('https://google.com');
const vpn = new URL('https://google.com');
const webSecurityScanner = new URL('https://google.com');

export {
  aiplatform,
  apianalytics,
  apigeeapiplatform,
  apigeesense,
  apimonetization,
  apis,
  appengine,
  armor,
  artifactRegistry,
  automl,
  beyondcorp,
  bigquery,
  bigtable,
  build,
  cdn,
  cloudDebugger,
  cloudRun,
  composer,
  computeEngine,
  containerOptimizedOs,
  dataCatalog,
  dataLab,
  dataLossPreventionApi,
  dataStudio,
  dataflow,
  dataprep,
  dataproc,
  datastore,
  deploymentManager,
  developerPortal,
  dialogflow,
  dns,
  eTpu,
  endpoints,
  errorReporting,
  externalIpAddresses,
  filestore,
  firestore,
  firewallRules,
  functions,
  generic,
  genomics,
  gke,
  gkeOnPrem,
  gpu,
  iam,
  interconnect,
  iotCore,
  jobsApi,
  keyAccessJustifications,
  loadBalancing,
  logging,
  memorystore,
  monitoring,
  naturalLanguageApi,
  network,
  partnerInterconnect,
  persistentDisk,
  premiumNetworkTier,
  pubSub,
  router,
  routes,
  securityCommandCenter,
  spanner,
  speechToText,
  sql,
  stackdriver,
  standardNetworkTier,
  storage,
  textToSpeech,
  toolsForPowershell,
  trace,
  transferAppliance,
  translationApi,
  videoIntelligenceApi,
  virtualPrivateCloud,
  visionApi,
  vpn,
  webSecurityScanner,
};
