// !!! DO NOT EDIT !!! -- automatically generated by scripts/assets.js

const browser = new URL('https://google.com');
const cassandra = new URL('https://google.com');
const component = new URL('https://google.com');
const consul = new URL('https://google.com');
const elasticsearch = new URL('https://google.com');
const firebase = new URL('https://google.com');
const kafka = new URL('https://google.com');
const mariadb = new URL('https://google.com');
const mongodb = new URL('https://google.com');
const mysql = new URL('https://google.com');
const nomad = new URL('https://google.com');
const postgres = new URL('https://google.com');
const user = new URL('https://google.com');
const users = new URL('https://google.com');
const vault = new URL('https://google.com');

export {
  browser,
  cassandra,
  component,
  consul,
  elasticsearch,
  firebase,
  kafka,
  mariadb,
  mongodb,
  mysql,
  nomad,
  postgres,
  user,
  users,
  vault,
};
