// !!! DO NOT EDIT !!! -- automatically generated by scripts/assets.js

const cRole = new URL('https://google.com');
const cm = new URL('https://google.com');
const controlPlane = new URL('https://google.com');
const crb = new URL('https://google.com');
const crd = new URL('https://google.com');
const cronjob = new URL('https://google.com');
const deploy = new URL('https://google.com');
const ds = new URL('https://google.com');
const ep = new URL('https://google.com');
const etcd = new URL('https://google.com');
const group = new URL('https://google.com');
const hpa = new URL('https://google.com');
const ing = new URL('https://google.com');
const job = new URL('https://google.com');
const limits = new URL('https://google.com');
const netpol = new URL('https://google.com');
const node = new URL('https://google.com');
const ns = new URL('https://google.com');
const pod = new URL('https://google.com');
const psp = new URL('https://google.com');
const pv = new URL('https://google.com');
const pvc = new URL('https://google.com');
const quota = new URL('https://google.com');
const rb = new URL('https://google.com');
const role = new URL('https://google.com');
const rs = new URL('https://google.com');
const sa = new URL('https://google.com');
const sc = new URL('https://google.com');
const secret = new URL('https://google.com');
const sts = new URL('https://google.com');
const svc = new URL('https://google.com');
const user = new URL('https://google.com');
const vol = new URL('https://google.com');

export {
  cRole,
  cm,
  controlPlane,
  crb,
  crd,
  cronjob,
  deploy,
  ds,
  ep,
  etcd,
  group,
  hpa,
  ing,
  job,
  limits,
  netpol,
  node,
  ns,
  pod,
  psp,
  pv,
  pvc,
  quota,
  rb,
  role,
  rs,
  sa,
  sc,
  secret,
  sts,
  svc,
  user,
  vol,
};
